version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: laundry-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: laundry
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laundry-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laundry-backend
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=laundry
      - JWT_SECRET=laundry-app-super-secure-secret-key-123456
      - JWT_EXPIRES_IN=1d
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - laundry-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: laundry-frontend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - laundry-network

volumes:
  postgres_data:

networks:
  laundry-network:
    driver: bridge 